---
- include_vars: archlinux.yml
- include_vars: users.yml
- name: Copy over pacman.conf
  copy:
    src: archlinux/pacman/pacman.conf
    dest: /etc/pacman.conf
    mode: 0444
    owner: root
    group: root
# TODO: import key
- name: Update
  pacman: upgrade=yes update_cache=yes
- name: Install packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"
- name: Remove nano
  pacman: state=absent name=nano
- name: Configure makepkg
  copy:
    src: archlinux/pacman/makepkg.conf
    dest: /etc/makepkg.conf
    mode: 0444
    owner: root
    group: root
- name: Add a folder for makepkg to hold packages in
  file:
    path: "~{{ item[0] }}/.local/pacman/{{ item[1] }}"
    state: directory
    owner: "{{ item[0] }}"
    group: "{{ item[0] }}"
  with_nested:
    - "{{ users }}"
    - [ pkg, src ]
- name: Install sudoers
  copy:
    src: archlinux/sudo/sudoers
    dest: /etc/sudoers
    mode: 0400
    owner: root
    group: root
- name: Configure pam_ssh_agent_auth
  copy:
    src: archlinux/sudo/sudo.pam.d
    dest: /etc/pam.d/sudo
    mode: 0444
    owner: root
    group: root
- name: Create directory for authorized_keys for pam_ssh_agent_auth
  file: mode=0700 owner=root group=root path=/etc/ssh/authorized_keys state=directory
- name: Install user ssh keys for pam_ssh_agent_auth
  template:
    src: authorized_keys.j2
    dest: "/etc/ssh/authorized_keys/{{ item }}"
    owner: root
    group: root
    mode: 0400
  with_items: "{{ users }}"
- name: Start zramswap
  service: name=zramswap state=started enabled=yes
