- include_vars: users.yml
- name: Checkout dotFiles
  git:
    repo: ssh://git@github.com/hi117/dotFiles
    dest: /usr/local/share/dotFiles
    recursive: yes
    depth: 1
    accept_hostkey: yes
    key_file: ~{{ansible_user_id}}/.ssh/githubKey
- name: Deploy dotFiles
  file:
      force: yes
      group: "{{ item[0] }}"
      owner: "{{ item[0] }}"
      path: "~{{ item[0] }}/{{ item[1] }}"
      src: "/usr/local/share/dotFiles/{{ item[1] }}"
      state: link
  with_nested:
    - "{{ users }}"
    - "{{ dotFiles }}"
- name: Deploy dircolors
  file:
    force: yes
    group: "{{ item }}"
    owner: "{{ item }}"
    path: "~{{ item }}/.dircolors"
    src: /usr/local/share/dotFiles/dircolors-solarized/dircolors.256dark
    state: link
  with_items: "{{ users }}"
- name: Deploy dotFiles to skel
  file:
    force: yes
    group: root
    owner: root
    path: "/etc/skel/{{ item }}"
    src: "/usr/local/share/dotFiles/{{ item }}"
    state: link
  with_items: "{{ dotFiles }}"
- name: Deploy dircolors to skel
  file:
    force: yes
    group: root
    owner: root
    path: "/etc/skel/.dircolors"
    src: /usr/local/share/dotFiles/dircolors-solarized/dircolors.256dark
    state: link
