- name: Add user specific groups
  group: name={{ item }} state=present
  with_items: {{ users }}
- name: Add users
  user:
    createhome: yes
    group: {{ item }}
    name: {{ item }}
    shell: /bin/zsh
  with_items: {{ users }}
- name: Add .ssh for users
  file: mode=0700 owner={{ item }} path=~{{ item }}/.ssh state=directory
  with_items: {{ users }}
- name: Deploy dotFiles
  file:
      force: yes
      group: "{{ item[0] }}"
      owner: "{{ item[0] }}"
  with_items: {{ users }}
